# Form implementation generated from reading ui file 'src/turbine_simulator_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(parent=self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 221, 651))
        self.treeWidget.setExpandsOnDoubleClick(False)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(240, 590, 1031, 71))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(240, 10, 1031, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(60, 50, 911, 421))
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Project"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Case"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Turbine Hydraulics"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "Load Data"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "Sizing"))
        self.treeWidget.topLevelItem(0).child(0).child(2).setText(0, _translate("MainWindow", "Surface Fit Settings"))
        self.treeWidget.topLevelItem(0).child(0).child(3).setText(0, _translate("MainWindow", "Output Options"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Performance Simulator"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "Maximised Output"))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "Manual/Automatic Control"))
        self.treeWidget.topLevelItem(0).child(1).child(2).setText(0, _translate("MainWindow", "Output Options"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Turbine Loads"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Status updates here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())


# Form implementation generated from reading ui file 'src/manual-automatic_control_widget.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormManualAutomaticControl(object):
    def setupUi(self, FormManualAutomaticControl):
        FormManualAutomaticControl.setObjectName("FormManualAutomaticControl")
        FormManualAutomaticControl.resize(400, 340)
        self.lineEdit_H_t = QtWidgets.QLineEdit(parent=FormManualAutomaticControl)
        self.lineEdit_H_t.setGeometry(QtCore.QRect(40, 120, 113, 22))
        self.lineEdit_H_t.setObjectName("lineEdit_H_t")
        self.label_H_t = QtWidgets.QLabel(parent=FormManualAutomaticControl)
        self.label_H_t.setGeometry(QtCore.QRect(40, 90, 101, 31))
        self.label_H_t.setObjectName("label_H_t")
        self.label_T_t_rate = QtWidgets.QLabel(parent=FormManualAutomaticControl)
        self.label_T_t_rate.setGeometry(QtCore.QRect(170, 90, 111, 31))
        self.label_T_t_rate.setObjectName("label_T_t_rate")
        self.lineEdit_H_t_rate = QtWidgets.QLineEdit(parent=FormManualAutomaticControl)
        self.lineEdit_H_t_rate.setGeometry(QtCore.QRect(170, 120, 113, 22))
        self.lineEdit_H_t_rate.setObjectName("lineEdit_H_t_rate")
        self.label_Q = QtWidgets.QLabel(parent=FormManualAutomaticControl)
        self.label_Q.setGeometry(QtCore.QRect(40, 30, 101, 31))
        self.label_Q.setObjectName("label_Q")
        self.lineEdit_Q_rate = QtWidgets.QLineEdit(parent=FormManualAutomaticControl)
        self.lineEdit_Q_rate.setGeometry(QtCore.QRect(170, 60, 113, 22))
        self.lineEdit_Q_rate.setObjectName("lineEdit_Q_rate")
        self.lineEdit_Q = QtWidgets.QLineEdit(parent=FormManualAutomaticControl)
        self.lineEdit_Q.setGeometry(QtCore.QRect(40, 60, 113, 22))
        self.lineEdit_Q.setObjectName("lineEdit_Q")
        self.label_Q_rate = QtWidgets.QLabel(parent=FormManualAutomaticControl)
        self.label_Q_rate.setGeometry(QtCore.QRect(170, 30, 111, 31))
        self.label_Q_rate.setObjectName("label_Q_rate")
        self.label_blade_angle = QtWidgets.QLabel(parent=FormManualAutomaticControl)
        self.label_blade_angle.setGeometry(QtCore.QRect(40, 150, 101, 31))
        self.label_blade_angle.setObjectName("label_blade_angle")
        self.lineEdit_blade_angle = QtWidgets.QLineEdit(parent=FormManualAutomaticControl)
        self.lineEdit_blade_angle.setGeometry(QtCore.QRect(40, 180, 113, 22))
        self.lineEdit_blade_angle.setObjectName("lineEdit_blade_angle")
        self.label_n = QtWidgets.QLabel(parent=FormManualAutomaticControl)
        self.label_n.setGeometry(QtCore.QRect(40, 210, 101, 31))
        self.label_n.setObjectName("label_n")
        self.lineEdit_n = QtWidgets.QLineEdit(parent=FormManualAutomaticControl)
        self.lineEdit_n.setGeometry(QtCore.QRect(40, 240, 113, 22))
        self.lineEdit_n.setObjectName("lineEdit_n")
        self.lineEdit_blade_angle_rate = QtWidgets.QLineEdit(parent=FormManualAutomaticControl)
        self.lineEdit_blade_angle_rate.setGeometry(QtCore.QRect(170, 180, 113, 22))
        self.lineEdit_blade_angle_rate.setObjectName("lineEdit_blade_angle_rate")
        self.label_blade_angle_rate = QtWidgets.QLabel(parent=FormManualAutomaticControl)
        self.label_blade_angle_rate.setGeometry(QtCore.QRect(170, 150, 111, 31))
        self.label_blade_angle_rate.setObjectName("label_blade_angle_rate")
        self.lineEdit_n_rate = QtWidgets.QLineEdit(parent=FormManualAutomaticControl)
        self.lineEdit_n_rate.setGeometry(QtCore.QRect(170, 240, 113, 22))
        self.lineEdit_n_rate.setObjectName("lineEdit_n_rate")
        self.label_n_rate = QtWidgets.QLabel(parent=FormManualAutomaticControl)
        self.label_n_rate.setGeometry(QtCore.QRect(170, 210, 111, 31))
        self.label_n_rate.setObjectName("label_n_rate")
        self.checkBox = QtWidgets.QCheckBox(parent=FormManualAutomaticControl)
        self.checkBox.setGeometry(QtCore.QRect(300, 120, 75, 20))
        self.checkBox.setObjectName("checkBox")
        self.groupBox = QtWidgets.QGroupBox(parent=FormManualAutomaticControl)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 361, 271))
        self.groupBox.setObjectName("groupBox")
        self.pushButtonApply = QtWidgets.QPushButton(parent=FormManualAutomaticControl)
        self.pushButtonApply.setGeometry(QtCore.QRect(300, 290, 81, 31))
        self.pushButtonApply.setObjectName("pushButtonApply")
        self.groupBox.raise_()
        self.lineEdit_H_t.raise_()
        self.label_H_t.raise_()
        self.label_T_t_rate.raise_()
        self.lineEdit_H_t_rate.raise_()
        self.label_Q.raise_()
        self.lineEdit_Q_rate.raise_()
        self.lineEdit_Q.raise_()
        self.label_Q_rate.raise_()
        self.label_blade_angle.raise_()
        self.lineEdit_blade_angle.raise_()
        self.label_n.raise_()
        self.lineEdit_n.raise_()
        self.lineEdit_blade_angle_rate.raise_()
        self.label_blade_angle_rate.raise_()
        self.lineEdit_n_rate.raise_()
        self.label_n_rate.raise_()
        self.checkBox.raise_()
        self.pushButtonApply.raise_()

        self.retranslateUi(FormManualAutomaticControl)
        QtCore.QMetaObject.connectSlotsByName(FormManualAutomaticControl)

    def retranslateUi(self, FormManualAutomaticControl):
        _translate = QtCore.QCoreApplication.translate
        FormManualAutomaticControl.setWindowTitle(_translate("FormManualAutomaticControl", "Form"))
        self.label_H_t.setText(_translate("FormManualAutomaticControl", "Target H [m]"))
        self.label_T_t_rate.setText(_translate("FormManualAutomaticControl", "Rate of Change [1/s]"))
        self.label_Q.setText(_translate("FormManualAutomaticControl", "Q [m³/s]"))
        self.label_Q_rate.setText(_translate("FormManualAutomaticControl", "Rate of Change [1/s]"))
        self.label_blade_angle.setText(_translate("FormManualAutomaticControl", "Blade Angle [°]"))
        self.label_n.setText(_translate("FormManualAutomaticControl", "n [rpm]"))
        self.label_blade_angle_rate.setText(_translate("FormManualAutomaticControl", "Rate of Change [1/s]"))
        self.label_n_rate.setText(_translate("FormManualAutomaticControl", "Rate of Change [1/s]"))
        self.checkBox.setText(_translate("FormManualAutomaticControl", "Activate"))
        self.groupBox.setTitle(_translate("FormManualAutomaticControl", "Input Parameters"))
        self.pushButtonApply.setText(_translate("FormManualAutomaticControl", "Apply"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormManualAutomaticControl = QtWidgets.QWidget()
    ui = Ui_FormManualAutomaticControl()
    ui.setupUi(FormManualAutomaticControl)
    FormManualAutomaticControl.show()
    sys.exit(app.exec())


